### ISSUE TITLE
Prebuilt PDFs

### ISSUE THREAD

**Issue by moll** [geertj/restful-api-design#11]
Hey!

I'd like to give REST-ful API Design a read, but prefer to do so through a PDF to make annotations on. Would you mind providing some precompiled PDFs (and possibly other formats for others)? I'm not so familiar with getting all of this Python stuff prepped and TeX ready etc. I assume you've got it all on your machine, so it's probably a lot easier for you to run `make pdf`. :-)

Thanks!

**Comment by boblehest** [comment]
If anyone else came here looking for other formats, there are (well hidden) links for them in the bottom right corner of the version hosted at https://restful-api-design.readthedocs.org.

Here's an image (with the relevant menu bearing the text "v: latest"): http://i.imgur.com/N65goy0.png

**Comment by moll** [comment]
Ah indeed. Thanks, @boblehest! Worthy of pointing this out somewhere more visible too perhaps, @geertj... :-)
